"""
G-code generator for converting turtle paths to G-code.
Produces Makelangelo-compatible G-code that is also parseable by
standard G-code viewers and other plotter software.
"""

import math
import re
from typing import List
from .turtle import Turtle, Point
from .plotter_settings import PlotterSettings


class GCodeGenerator:
    """Generates G-code from Turtle paths."""

    def __init__(self, settings: PlotterSettings):
        self.settings = settings

    def turtle_to_gcode(self, turtle: Turtle) -> List[str]:
        """Convert a Turtle's paths to G-code.

        Produces standards-compliant G-code compatible with:
        - Makelangelo firmware
        - Universal G-code Sender
        - bCNC, CNCjs, and other G-code senders
        - Inkscape G-code extensions
        """
        gcode = []

        feed_travel = self.settings.get('feed_rate_travel')
        feed_draw = self.settings.get('feed_rate_draw')

        # Header
        gcode.append('; Generated by Polargraph')
        gcode.append('; Makelangelo-compatible G-code')
        gcode.append(f'; Feed rate travel: {feed_travel} mm/min')
        gcode.append(f'; Feed rate draw: {feed_draw} mm/min')
        gcode.append('')
        gcode.append('G21 ; Units: millimeters')
        gcode.append('G90 ; Absolute positioning')
        gcode.append(f'G0 F{feed_travel} ; Set travel speed')
        gcode.append(f'G1 F{feed_draw} ; Set draw speed')

        # Pen up to start
        self._push_pen_up(gcode)

        last_point = None
        pen_is_up = True
        # Track last feed mode to avoid redundant G0/G1 switches
        last_was_travel = True

        for layer in turtle.layers:
            for line in layer.lines:
                if len(line.points) < 2:
                    continue

                # Move to start of line (travel move)
                start = line.points[0]

                if last_point is None or self._distance(last_point, start) > 0.1:
                    # Pen up if not already
                    if not pen_is_up:
                        self._push_pen_up(gcode)
                        pen_is_up = True

                    # Travel to start
                    gcode.append(f'G0 X{start.x:.3f} Y{start.y:.3f}')
                    last_was_travel = True

                # Pen down
                if pen_is_up:
                    self._push_pen_down(gcode)
                    pen_is_up = False

                # Draw line segments
                for i in range(1, len(line.points)):
                    point = line.points[i]
                    gcode.append(f'G1 X{point.x:.3f} Y{point.y:.3f}')
                    last_was_travel = False

                last_point = line.points[-1]

        # Footer - pen up, then return home
        gcode.append('')
        gcode.append('; End of drawing')
        self._push_pen_up(gcode)
        gcode.append(f'G0 X0 Y0 ; Return home')

        return gcode

    def gcode_to_turtle(self, gcode: List[str]) -> Turtle:
        """Parse G-code back into a Turtle for preview.

        Handles:
        - G0/G00 rapid moves (pen up/travel)
        - G1/G01 linear moves (pen down/draw)
        - G2/G02, G3/G03 arc moves (CW/CCW)
        - G90/G91 absolute/relative positioning
        - M280 servo commands for pen up/down
        - M3/M5 spindle commands (alternative pen control)
        - Z-axis moves for pen lift
        - Parenthesized comments and semicolon comments
        """
        turtle = Turtle()

        current_x = 0.0
        current_y = 0.0
        pen_down = False
        absolute_mode = True

        up_angle = self.settings.get('pen_angle_up')
        down_angle = self.settings.get('pen_angle_down')
        pen_threshold = (up_angle + down_angle) / 2

        for line in gcode:
            line = line.strip()

            # Skip empty lines
            if not line:
                continue

            # Remove parenthesized comments: (comment)
            line = re.sub(r'\([^)]*\)', '', line)

            # Remove semicolon comments
            if ';' in line:
                line = line[:line.index(';')].strip()

            if not line:
                continue

            # Parse command
            parts = line.upper().split()
            if not parts:
                continue

            cmd = parts[0]
            params = self._parse_params(parts[1:])

            # Also check for combined format like G0X10Y20
            if len(parts) == 1 and len(cmd) > 3:
                params = self._parse_params_from_string(line.upper())
                cmd_match = re.match(r'[GM]\d+', line.upper())
                if cmd_match:
                    cmd = cmd_match.group()

            if cmd in ('G0', 'G00'):
                # Rapid move (travel - pen should be up)
                new_x = current_x
                new_y = current_y

                if 'X' in params:
                    new_x = params['X'] if absolute_mode else current_x + params['X']
                if 'Y' in params:
                    new_y = params['Y'] if absolute_mode else current_y + params['Y']

                # Z-axis pen control (positive Z = pen up)
                if 'Z' in params:
                    z_val = params['Z']
                    if z_val > 0 and pen_down:
                        turtle.pen_up_cmd()
                        pen_down = False
                    elif z_val <= 0 and not pen_down:
                        turtle.pen_down()
                        pen_down = True

                if pen_down:
                    turtle.move_to(new_x, new_y)
                else:
                    turtle.position.x = new_x
                    turtle.position.y = new_y

                current_x, current_y = new_x, new_y

            elif cmd in ('G1', 'G01'):
                # Linear move (draw)
                new_x = current_x
                new_y = current_y

                if 'X' in params:
                    new_x = params['X'] if absolute_mode else current_x + params['X']
                if 'Y' in params:
                    new_y = params['Y'] if absolute_mode else current_y + params['Y']

                # Z-axis pen control
                if 'Z' in params:
                    z_val = params['Z']
                    if z_val > 0 and pen_down:
                        turtle.pen_up_cmd()
                        pen_down = False
                    elif z_val <= 0 and not pen_down:
                        turtle.pen_down()
                        pen_down = True

                if not pen_down:
                    turtle.pen_down()
                    pen_down = True

                turtle.move_to(new_x, new_y)
                current_x, current_y = new_x, new_y

            elif cmd in ('G2', 'G02', 'G3', 'G03'):
                # Arc moves: G2 = clockwise, G3 = counter-clockwise
                clockwise = cmd in ('G2', 'G02')

                end_x = params.get('X', current_x)
                end_y = params.get('Y', current_y)
                if not absolute_mode:
                    end_x += current_x
                    end_y += current_y

                if not pen_down:
                    turtle.pen_down()
                    pen_down = True

                if 'I' in params or 'J' in params:
                    # I, J are offsets from current position to arc center
                    cx = current_x + params.get('I', 0)
                    cy = current_y + params.get('J', 0)

                    # Calculate start and end angles
                    start_angle = math.atan2(current_y - cy, current_x - cx)
                    end_angle = math.atan2(end_y - cy, end_x - cx)
                    radius = math.sqrt((current_x - cx)**2 + (current_y - cy)**2)

                    if clockwise:
                        if end_angle >= start_angle:
                            end_angle -= 2 * math.pi
                    else:
                        if end_angle <= start_angle:
                            end_angle += 2 * math.pi

                    # Discretize arc
                    arc_length = abs(end_angle - start_angle) * radius
                    segments = max(8, int(arc_length / 0.5))

                    for i in range(1, segments + 1):
                        t = i / segments
                        angle = start_angle + t * (end_angle - start_angle)
                        px = cx + radius * math.cos(angle)
                        py = cy + radius * math.sin(angle)
                        turtle.move_to(px, py)

                elif 'R' in params:
                    # R format: radius given directly
                    r = params['R']
                    # Simplified: just draw a line for R-format arcs
                    turtle.move_to(end_x, end_y)

                current_x, current_y = end_x, end_y

            elif cmd == 'G90':
                absolute_mode = True

            elif cmd == 'G91':
                absolute_mode = False

            elif cmd == 'M280':
                # Servo control - detect pen up/down
                if 'S' in params:
                    angle = params['S']
                    if abs(angle - up_angle) < abs(angle - down_angle):
                        if pen_down:
                            turtle.pen_up_cmd()
                            pen_down = False
                    else:
                        if not pen_down:
                            turtle.pen_down()
                            pen_down = True

            elif cmd in ('M3', 'M03'):
                # Spindle on = pen down (alternative convention)
                if not pen_down:
                    turtle.pen_down()
                    pen_down = True

            elif cmd in ('M5', 'M05'):
                # Spindle off = pen up (alternative convention)
                if pen_down:
                    turtle.pen_up_cmd()
                    pen_down = False

        return turtle

    def _parse_params(self, parts: List[str]) -> dict:
        """Parse G-code parameters from space-separated parts."""
        params = {}
        for part in parts:
            if len(part) > 1:
                letter = part[0]
                try:
                    value = float(part[1:])
                    params[letter] = value
                except ValueError:
                    pass
        return params

    def _parse_params_from_string(self, line: str) -> dict:
        """Parse G-code parameters from a continuous string like G0X10Y20."""
        params = {}
        for match in re.finditer(r'([A-Z])(-?[\d.]+)', line):
            letter = match.group(1)
            try:
                params[letter] = float(match.group(2))
            except ValueError:
                pass
        return params

    def _push_pen_up(self, gcode: List[str]):
        """Pen up: flush move buffer, actuate servo, dwell for servo travel.

        Uses M280 (direct servo, bypasses motion planner) with G4 dwells.
        NOTE: Makelangelo firmware G4 passes P*1000 to pause() which expects
        microseconds, so P800 = 800*1000us = 800ms of actual dwell.
        """
        up_angle = self.settings.get('pen_angle_up')
        gcode.append('G4 P0 ; Flush move buffer')
        gcode.append(f'M280 P0 S{up_angle} ; Pen up')
        gcode.append('G4 P800 ; Wait for servo')

    def _push_pen_down(self, gcode: List[str]):
        """Pen down: flush move buffer, actuate servo, dwell for servo travel."""
        down_angle = self.settings.get('pen_angle_down')
        gcode.append('G4 P0 ; Flush move buffer')
        gcode.append(f'M280 P0 S{down_angle} ; Pen down')
        gcode.append('G4 P800 ; Wait for servo')

    def _distance(self, p1: Point, p2: Point) -> float:
        """Calculate distance between two points."""
        dx = p2.x - p1.x
        dy = p2.y - p1.y
        return (dx * dx + dy * dy) ** 0.5
